name: macOS

on:
  pull_request:
    branches:
      - testing

jobs:
  build:
    strategy:
      matrix:
        os: [macOS-latest]
        arch: [x86_64, arm64]

    runs-on: ${{ matrix.os }}

    concurrency:
        group: ${{ github.ref }}-${{ github.base_ref }}-${{ github.head_ref }}-macOS-${{ matrix.kind }}
        cancel-in-progress: true
    steps:
      - uses: actions/checkout@v3
      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest
      - name: Build
        run: |
          xmake f --arch=${{ matrix.arch }}
          xmake -vD
      - name: Search
        run: |
          find .
      - name: Package
        run: |
          cd build/macosx/${{ matrix.arch }}/release/ && zip -r xavine-macos-${{ matrix.arch }}.zip * && mv xavine-macos-${{ matrix.arch }}.zip ../../../../
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: |
            xavine-macos-${{ matrix.arch }}.zip
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
          generateReleaseNotes: true
          tag: ${{ github.event.pull_request.title }}
          omitBodyDuringUpdate: true
          prerelease: true
          replacesArtifacts: true